# settings
name: train_vqir_stage1_debug
model_type: VQIRModel
gpu_ids: [0]
ir_scale: &f 16 # 16 or 32
manual_seed: 1026
syncbn: true # must set to true to avoid bn inplace revision

datasets:
  train:
    name: DIV2K
    mode: LRHR
    dataroot_HR: # path to the HR train dataset
    dataroot_LR: # path to the LR train dataset
    HR_size: 256
    n_workers: 16
    batch_size: 16
    use_shuffle: true
    use_flip: true
    use_rot: true
    subset_file: ~

  val:
    # Please modify accordingly to use your own validation
    # Or comment the val block if do not need validation during training
    name: DIV2K
    mode: LRHR
    dataroot_HR: # path to the HR valid dataset
    dataroot_LR: # path to the LR valid dataset

# network structures
network_ir:
  type: VQIR
  stage: 1
  ir_scale: *f
  ch: 128
  ch_mult: [ 1,1,2,2,4 ]
  in_channels: 3
  out_channels: 3
  z_channels: 256
  embed_dim: 256
  n_embed: 1024
  num_res_blocks: 2
  double_z: false

# path
path:
  pretrain_network_ir: # path to the pre-trained VQGAN model
  strict_load_ir: false

  resume_state: ~
  ignore_resume_networks: ~

# training settings
train:
  optim_ir_enc:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.96 ] # align with taming

  scheduler:
    type: MultiStepLR
    milestones: [ 200000 ]
    gamma: 1

  total_iter: 500000
  warmup_iter: -1  # no warm up
    
  guide_opt:
    type: MSELoss
    loss_weight: !!float 0.5
    reduction: mean

  feature_opt:
    type: MSELoss
    loss_weight: !!float 1.0
    reduction: mean

  gram_opt:
    type: GramLoss
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  fidelity_ratio: 1.0
  metrics:
    sr_psnr:
      type: calculate_psnr
      crop_border: *f
      test_y_channel: true

    dr_psnr: 
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

    sr_ssim: 
      type: calculate_ssim
      crop_border: *f
      test_y_channel: true
      
    dr_ssim: 
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true

    sr_lpips:
      type: calculate_lpips

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
find_unused_parameters: True
